name: Reusable Deploy Minor

  # not on push or workflow_dispatch, but this workflow will be used on 
  # workflow_call by another workflow.

## iteration 1 below:

#on: workflow_call
#jobs:
#    deploy:
#      runs-on: ubuntu-latest
#      steps:
#        - name: Output information
#          run: echo "Deploying and uploading first iterantino of reusable deploy minor"




## iteration 2 below, recall in the build job of the use-the-reusable that we generate
## the artifacts and upload the artifacts from that runner to github
## we now want to download these artifacts like the original deploy did to this REUSABLE deploy runner
## hardcoding the download name to dist-files like in the original is not good because this yml would no longer
## be generally reusable.  Needs to be dynamic.
## we must get artifact name from the use-the-reusable as an input
## the name is "artifact-name"

on: 
  workflow_call:
    inputs:
    # this is a reserved word inputs
      artifact-name:
      # this is the name of the input that we have chosen
        description: The name of the deployable artifact files from the use-the-reusable
        required: false
        #true means the workflow will fail if we are missing this input
        #false means workflow will not fail even if we are missing this artifact input
        default: dist
        # dist will be the artifact value if it is missing
        type: string

    outputs:
      result:
      # this is the name you give the output
        description: The result of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}
        # jobs is another context. It can only be used in reusable workflows
        # https://docs.github.com/en/actions/learn-github-actions/contexts#jobs-context
        # this value is from the jobs.deploy.outputs.outcome directly below
        # the output of the deploy job was configured as below so that it could be referenced here as a final output of 
        # this reusable workflow deploy job.  This is the result output of this entire workflow


#secrets at the same level as inputs: and outputs: above
#    secrets:
#      # some-secret:
#        # required: false

jobs:
  deploy:
    outputs:
    # this is an output of the deploy job
      outcome: ${{ steps.set-result.outputs.step-result }}
# this uses the steps context. "step-result" is the name used below for the result of the deployment

    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          # this is the inputs context
          # https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context
          # The inputs context contains input properties passed to an action, to a reusable workflow, or to a manually triggered workflow. 
          # "artifact-name" is from the inputs above

      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading..."
      - name: Set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
        # use this new syntax
        # step-result is the name of the result for this step